version: "3.8"
services:
  balancer:
    image: balancer:0.1.0-SNAPSHOT
    environment:
      - BIND_PORT=5000
      - MAX_PROVIDERS=10
    ports:
      - "8080:5000"
    networks:
      - load-balancing

  provider:
    image: provider:0.1.0-SNAPSHOT
    depends_on:
      - "balancer"
    environment:
      - BIND_PORT=5000
      - LB_HOST=http://balancer:5000/provider
      - MAX_CONCURRENT_REQESTS=10
    networks:
      - load-balancing

networks:
  load-balancing: